### ISSUE TITLE
Docs do not generate on Elixir 1.8.x

### ISSUE THREAD

**Issue by jbrowning** [parroty/extwitter#112]
Tested on Elixir 1.8.1.

```
$ mix docs
...
** (RuntimeError) module ExTwitter.API.Auth was not compiled with flag --docs
    (ex_doc) lib/ex_doc/retriever.ex:152: ExDoc.Retriever.export_docs?/1
    (ex_doc) lib/ex_doc/retriever.ex:136: ExDoc.Retriever.get_module/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc) lib/ex_doc/retriever.ex:116: ExDoc.Retriever.docs_from_modules/2
    (ex_doc) lib/ex_doc.ex:101: ExDoc.generate_docs/3
    (ex_doc) lib/mix/tasks/docs.ex:159: anonymous fn/6 in Mix.Tasks.Docs.run/3
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc) lib/mix/tasks/docs.ex:158: Mix.Tasks.Docs.run/3
```

**Comment by Mdlkxzmcp** [comment]
This started happening from 1.7.0-rc.0

**Comment by parroty** [comment]
Thanks for reporting and sorry being late to respond. Updated the dependencies with the commit above.
