### ISSUE TITLE
Crash when calling user_lookup on more than 2 twitter IDs

### ISSUE THREAD

**Issue by jlarigakis** [parroty/extwitter#78]
To reproduce:

`ExTwitter.user_lookup([783214, 10230812, 507309896])`

Result:
```
** (UnicodeConversionError) invalid code point 10230812
       (elixir) lib/list.ex:727: List.to_string/1
       (elixir) lib/enum.ex:1755: Enum."-join/2-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1755: Enum.join/2
    (extwitter) lib/extwitter/parser.ex:119: anonymous fn/1 in ExTwitter.Parser.parse_batch_user_lookup_params/1
       (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (extwitter) lib/extwitter/api/users.ex:32: ExTwitter.API.Users.user_lookup/2
```

**Comment by parroty** [comment]
Thanks for the PR. The change is merged and pushed. I'm closing at the moment, but if you find any remaining issues, please reopen or open another one.

**Comment by jlarigakis** [comment]
Thanks for the quick merge!
